// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package posts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"sensetion/go-fiber/views/entities/card"
	"sensetion/go-fiber/views/shared/ui/decorativeElms"
	"sensetion/go-fiber/views/shared/ui/title"
)

type PostsProps struct {
	IsPopular bool
	IsLast    bool
}

func Posts(props PostsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = PostsCSS(props).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.IsPopular == true {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"margin-top: 60px;\"><div class=\"posts-container__title\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = decorativeElms.Rectangle().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = title.Title(title.TitleProps{
				Text: "Популярное",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"posts-container\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, p := range getPopularPosts() {
				templ_7745c5c3_Err = card.CardM(card.CardMProps{
					TitleText:    p.TitleText,
					SubTitleText: p.SubTitleText,
					IMGSrc:       p.IMGSrc,
					AvatarSrc:    p.AvatarSrc,
					UserName:     p.UserName,
					DateText:     p.DateText,
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func PostsCSS(props PostsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<style>\r\n\t\t.posts-container{\r\n\t\t\tdisplay: flex;\r\n\t\t\talign-items: center;\r\n\t\t\twidth: 100%;\r\n\t\t\tgap: 24px;\r\n\t\t}\r\n\r\n\t\t.posts-container__title{\r\n\t\t\tdisplay: flex;\r\n\t\t\talign-items: center;\r\n\t\t\tgap: 6px;\r\n\t\t\tmargin-bottom: 38px;\r\n\t\t}\r\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getPopularPosts() []card.CardMProps {
	return []card.CardMProps{
		{
			TitleText:    "Открытие сезона байдарок",
			SubTitleText: "Сегодня был открыт сезон путешествия на байдарках, где вы можете поучаствовать в ...",
			UserName:     "Михаил Аршинов",
			DateText:     "Август 18 , 2025",
			IMGSrc:       "/public/images/posts/sport.png",
			AvatarSrc:    "/public/images/avatar/unsplash_ZHvM3XIOHoE.png",
		},
		{
			TitleText:    "Выбери правильный ноутбук для задач",
			SubTitleText: "От верного выбора ноутбука зависит не только удобство, но и эффективность работы...",
			UserName:     "Вася Программист",
			DateText:     "Июль 25 , 2025",
			IMGSrc:       "/public/images/posts/unsplash_mP7aPSUm7aE.png",
			AvatarSrc:    "/public/images/avatar/unsplash_kq8dGNS1lLk.png",
		},
		{
			TitleText:    "Создание автомобилей с автопилотом",
			SubTitleText: "Электрические автомобили без водителя скоро станут реальностью, где нам не придётся ...",
			UserName:     "Мария",
			DateText:     "Июль 14 , 2025",
			IMGSrc:       "/public/images/posts/unsplash_-js8KGQLfhw.png",
			AvatarSrc:    "/public/images/avatar/unsplash_0wRXAXqIp58.png",
		},
		{
			TitleText:    "Как быстро приготовить вкусный обед",
			SubTitleText: "Сегодня поговорим о том, как можно быстро и эффективно приготовить обед для ...",
			UserName:     "Ли Сюн",
			DateText:     "Май 10 , 2025",
			IMGSrc:       "/public/images/posts/unsplash_DGHy9KgdTj0.png",
			AvatarSrc:    "/public/images/avatar/unsplash_L2dTmhQzx4Q.png",
		},
	}
}

var _ = templruntime.GeneratedTemplate
